INSERT INTO categoria(nome, descrizione) VALUES
                                             ('Informatica', 'Computer, tablet e tanto altro!'),
                                             ('Telefonia', 'Cellulari di ultimissima generazione!'),
                                             ('Accessori', 'Per ampliare il tuo inventario tech, scegli i nostri accessori');

INSERT INTO prodotto(nome, marca, colore, prezzo_listino, descrizione, batteria, ram_tipo, ram_quantita, sistema_operativo, cpu_nome, disponibilita)
VALUES
    ('Redmi Note 9S', 'Xiaomi', 'Azzurro', 180, 'Touchscreen da 6.67 pollici, fortemente votato all\'imaging. Risoluzione di 2400x1080 pixel', 1, 'DDR3', '4 GB', 'Android 10', 'Snapdragon 720G', 20),
    ('Redmi Note 9', 'Xiaomi', 'Viola', 115, 'Touchscreen da 6.53 pollici, non ha molto da invidiare ai dispositivi più avanzati. Risoluzione di 2340x1080 pixel', 1,'DDR3', '3 GB', 'Android 10', 'Helio G85 MediaTek', 15),
    ('Galaxy M13', 'Samsung', 'Nero', 139, 'Touchscreen da 6.6 pollici che pone questo Samsung al vertice della categoria. Risoluzione di 1600x720 pixel', 1, 'DDR3', '4 GB', 'Android 12', 'SAMSUNG Exynos 850', 18),
    ('Galaxy XCover6 Pro', 'Samsung', 'Nero', 600, 'Touchscreen da 6.6 pollici, è in grado di soddisfare anche l\'utente più esigente. Risoluzione di 2408x1080', 1, 'DDR3', '6 GB', 'Android 12', 'Snapdragon 778G', 25),
    ('iPhone 13','Apple', 'Bianco', 760, 'Display da 6.1 pollici con risoluzione di 2532x1170, ha molte funzionalità e all\'avanguardia, come il modulo 5G', 1, 'DDR3', '4 GB', 'iOS 15', 'Apple A15 Bionic', 22),
    ('iPhone 12 Pro', 'Apple', 'Nero', 920, 'Display da 6.1 pollici con una risoluzione di 2532x1170 pixel, è uno degli smartphone iOS più avanzati e comleti che ci siano in circolazione', 1, 'DDR3', '6 GB', 'iOS 14', 'Apple A14 Bionic', 17),
    ('Nova 10', 'Huawei', 'Nero', 500, 'Touchscreen da 6.67 pollici con risoluzione di 2400x1080 pixel, sul versante delle funzionalità a questo telefono non manca davvero nulla', 1, 'DDR3', '8 GB', 'HarmonyOS 2.0', 'Snapdragon 778G', 23),
    ('Enjoy 50', 'Huawei', 'Bianco', 300, 'Touchscreen da 6.75 pollici con risoluzione di 1600x720 pixel. Cellulare di fascia media, è ideale per chi non ha troppe pretese ma che non vuole rinunciare ad un bel display touchscreen', 1, 'DDR3', '6 GB', 'HarmonyOS', 'Huawei HiSilicon710A', 26),
    ('12 Lite', 'Xiaomi', 'Nero', 460, 'Touchscreen da 6.55 pollici con risoluzione di 2400x1080 pixel. Smartphone di buon livello, è dotato del modulo 5G che permette un trasferimento dati eccellente', 1, 'DDR3', '6 GB', 'Android 12', 'Snapdragon 778G', 16),
    ('Galaxy Quantum 3', 'Samsung', 'Nero', 460, 'Touchscreen da 6.7 pollici con risoluzione da 2400x1080 pixel. Ha pochi competitor per la multimedialità, grazie alla fotocamera da 108 megapixel', 1, 'DDR3', '8 GB', 'Android 12', 'MediaTek MT6877', 24),
    ('iPhone SE', 'Apple', 'Bianco', 400, 'Display da 4.7 pollici con un\'ottima risoluzione di 1334x750 pixel. Funzionalità all\'avanguardia come il modulo 5G fanno dell\'iPhone SE uno smartphone iOS avanzato', 1, 'DDR3', '4 GB', 'iOS 15', 'Apple A15 Bionic', 12),
    ('Nova Y90', 'Huawei', 'Nero', 245, 'Touchscreen da 6.7 pollici con risoluzione 2388x1080 pixel. Telefono completo, con tante funzionalità che non ha da invidiare ai cellulari top di gamma', 1, 'DDR3', '8 GB', 'EMUI 12', 'Snapdragon 680', 14),
    ('P Smart 2021', 'Huawei', 'Bianco', 140, 'Smartphone di buon livello, con un touchscreen da 6.67 pollici e una risoluzione di 2400x1080 pixel. Con il modulo LTE 4G, permette una navigazione internet eccellente', 1, 'DDR3', '4 GB', 'Android 10', 'Huawei HiSilicon710A', 22),
    ('12S', 'Xiaomi', 'Nero', 700, 'Smartphone di buon livello, con touchscreen da 6.28 pollici e risoluzione di 2400x1080 pixel. La fotocamera da 50 megapixel permette a questo telefono di avere pochi competitor', 1, 'DDR3', '8 GB', 'Android 12', 'SnapDragon 8 Plus', 14),
    ('Galaxy A53 5G', 'Samsung', 'Bianco', 300, 'Soddisfa anche l\'utente più esigente con il touchscreen da 6.5 pollici e una risoluzione di 2400x1080 pixel. Il modul 5G permette una connettività eccellente', 1, 'DDR3', '6 GB', 'Android 12', 'Samsung Exynos1280', 13),
    ('12 Pro Max','Apple', 'Nero', 1090, 'Semplice e completo, ha un display di 6.7 pollici con una risoluzione di 2778x1284 pixel. La risoluzione delle foto è di 4000x3000 pixel, e registra video in 4K', 1, 'DDR3', '6 GB', 'iOS 14', 'Apple A14 Bionic', 16),
    ('Vivobook 14 K413', 'Asus','Nero', 799, 'Con un processore Intel Core di undicesima generazione e grafica Intel Iris X, velocità e intelligenza per risparmiare tempo, oltre che una connettività veloce e affidabile', 1, 'DDR3', '8 GB', 'Windows 10 Home', 'Intel Core i5', 5),
    ('Chromebook C423NA-EB0354', 'Asus', 'Silver', 229, 'Semplicità, sicurezza, velocità. Con il tasto tuttofare, i Chromebook ti aiutano a trovare tutto ciò che ti serve, come file, app e risposte online. Trovi tutto ciò che ti serve in un unico posto', 1, 'DDR3', '4 GB', 'Chrome OS', 'Intel Celeron', 7),
    ('Aspire 3 A315-58-51RV', 'Acer', 'Silver', 499, 'A scuola, a casa, al lavoro: tutte le operazioni di cui hai bisogno con i più recenti processori Intel o AMD, senza interrompere le applicazioni in esecuzione', 1, 'DDR3', '8 GB', 'Windows 11 Home', 'Intel Core i5', 8),
    ('MacBoox Pro 14', 'Apple', 'Silver', 2119, 'Potenza allo stato Pro con i velocissimi chip M1 Pro o M1 Max, capaci di performance rivoluzionarie con un\'incredibile durata della batteria', 1, 'DDR3', '16 GB', 'macOS', 'Apple M1 Pro', 4),
    ('15S-FQ4024NL', 'HP', 'Silver', 649, 'Esperienza straordinaria, con una visualizzazione in una cornice micro-edge di soli 6,5 mm. Design sottile e leggero, per portare il PC con te, ovunque', 1, 'DDR3', '8 GB', 'Windows 11 Home', 'Intel Core i7', 6),
    ('Ideapad 3 15IML05', 'Lenovo', 'Platinum Grey', 599, 'Notebook con potenza sufficiente a svolgere ogni attività. I processori Intel Core di ultima generazione all\'avanguardia favoriscono prestazioni veloci ed eccezionale esperienza di intrattenimento', 1, 'DDR3', '12 GB', 'Windows 11 Home', 'Intel Core i5', 8),
    ('Redmi Buds 3 Lite', 'Xiaomi', 'Nero', 20, 'Auricolare con tecnologia wireless fino a 10 metri! Ideale per musica e chiamate',1, NULL, NULL, 'Proprietario', NULL, 25),
    ('Mi True Wireless Earphones 2 Basic', 'Xiaomi', 'Bianco', 23.90, 'Raccomandate per la musica, offrono un\'esperienza di ascolto straordinaria', 1, NULL, NULL, 'Proprietario', NULL, 19),
    ('AirPods terza generazione', 'Apple', 'Bianco', 179,'Leggeri e affusolati, gli AirPods sono perfettamente angolati per darti più comfort e dirigere meglio l\'audio verso l\'orecchio', 1, NULL, NULL, 'Proprietario', NULL, 9),
    ('Apple Watch Series 3 GPS', 'Apple', 'Nero', 199, 'Tieni d\'occhio la tua salute, misura i tuoi allenamenti, trova la motivazione per raggiungere i tuoi obiettivi di fitness', 1, 'DDR3', '8 GB', 'watchOS 5', NULL, 5),
    ('Galaxy Watch 4', 'Samsung', 'Nero', 279, 'Smartwatch completo per monitorare la tua salute e il tuo allenamento. Con il suo cinturino in silicone, offre comodità e sicurezza', 1, 'DDR3', '16 GB', 'Wear OS', NULL, 6),
    ('Redmi Watch 2 Lite', 'Xiaomi', 'Nero', 69.99, 'Con display touch, 17 modalità di allenamento e resistenza all\'acqua, è uno smartwatch completo e performante', 1, NULL, NULL, 'Xiaomi OS', NULL, 5),
    ('Mi Smart Band 6', 'Xiaomi', 'Nero', 34.95, 'Display AMOLED, che controlla facilmente messaggi, chiamate e notifiche. Elegante forma e servizi all\'avanguardia: monitoraggio del sonno, dello stress e della salute', 1, NULL, NULL, 'Proprietario', NULL, 12);
INSERT INTO appartenere VALUES
(1,17),
(1,18),
(1,19),
(1,20),
(1,21),
(1,22),
(2,1),
(2,2),
(2,3),
(2,4),
(2,5),
(2,6),
(2,7),
(2,8),
(2,9),
(2,10),
(2,11),
(2,12),
(2,13),
(2,14),
(2,15),
(2,16),
(3,23),
(3,24),
(3,25),
(3,26),
(3,27),
(3,28),
(3,29);

